# Generated by Django 5.0.6 on 2024-06-10 01:54

import music.directories
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_favoritelist_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='coverImage',
            field=models.ImageField(upload_to=music.directories.CreateDirectory.playlist_directory_path),
        ),
    ]
